<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>LlrpReaderPlatform.Services</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpReaderPlatform.Contracts\Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LlrpSdk" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

</Project>
