<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <RootNamespace>LlrpReaderPlatform.Extensions.Impinj</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LlrpReaderPlatform.Contracts\Contracts.csproj" />
    <ProjectReference Include="..\LlrpReaderPlatform.Services\Services.csproj" />
    <PackageReference Include="LlrpSdk.Extensions.Impinj" />
  </ItemGroup>

</Project>
