<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsTestProject>false</IsTestProject>
    <RootNamespace>LlrpReaderPlatform.Hardware.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/LlrpReaderPlatform.Infrastructure/Infrastructure.csproj" />
  </ItemGroup>

</Project>
